### ISSUE TITLE
PERMANOVA issue

### ISSUE THREAD

**Issue by matteopaccagnella** [UriaMorP/tcam_analysis_notebooks#1]
Dear Dr. Uria I am a biotech from Italy and I am really interested in your code that could help to investigate my longitudinal omics data, but when I try to compute data on jupyter notebook I can't reproduce PERMANOVA analysis. In particular seems that I have a problem with multiprocessing function. Do you encounter a similar issue and in case have any suggestions?
Thank you very much in advance for helping.
![issue_permanova](https://user-images.githubusercontent.com/32670732/209785965-7d3103b6-cf0c-4bb3-bd46-3ebb7e19e6c1.jpg)

Matteo

**Comment by UriaMorP** [comment]
Hi @matteopaccagnella , thanks for contacting us. 
So far, we did not encounter this error.

It seems that the interpreter cannot locate a function called `_permfs`. This is a helper function passed as first argument to the high-order function `imap` from the multiprocessing module. So the first thing I'd do is to make sure that the cell containing `_permfs` definition is evaluated:
```python
def _permfs(args):
    __data, tv, N, permdict = args
    _data = __data.copy()
    _data['rGroup11'] = _data['Participant1'].map(permdict)
    _data['rGroup22'] = _data['Participant2'].map(permdict)
    return Fstat(_data, tv, N)
```

That said,  I see that you use Windows and we did not check if our code runs on this operating system. So I have no way for knowing for sure if this is an OS problem or not. 

You can always convert the `with Pool...` statement to a `for` loop thus avoiding any use of the multiprocessing module. This should definitely work (don't know how long will it take for the PERMANOVA to run though...)

**Comment by UriaMorP** [comment]
I ported the code for reproducing results related to Suez2018 notebook to colab. you can use this link: https://colab.research.google.com/drive/1a3bsAypzIiXIhnOrB7GqsnQKjOnCfuKu?usp=sharing 

Seems to work over there.

**Comment by matteopaccagnella** [comment]
It works! Thank you very much! I could use colab also eventually for my
data eventually in future?

Dr.Matteo Paccagnella
Fondazione Arco (CN)
Laboratorio di Oncologia Traslazionale
Fax. 0171/616331
Ospedale Carle, via Carle 25 –
12100 Confreria - Cuneo Tel. 0171/616342


Il giorno mer 28 dic 2022 alle ore 10:34 Uria Mor ***@***.***>
ha scritto:

**Comment by UriaMorP** [comment]
Thrilled to hear that it works for you. I'll close the issue now.

Regarding using colab for your data, I'm no expert, and don't know what data you work with so I don't feel comfortable making any suggestions or recommendations.
